server:
  port: 9093
spring:
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      database: delivery
  activemq:
    packages:
      trust-all:
integration:
  client:
    url: http://localhost:9092
