CREATE TABLE usuario (
id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
email VARCHAR(40) NOT NULL,
nome VARCHAR(45) NOT NULL,
idade INT(3) NOT NULL,
senha VARCHAR(45) NULL,
telefone VARCHAR(45) NOT NULL,
is_active TINYINT(1) NOT NULL);
